apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasksappui
  labels:
    app: tasksappui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasksappui
  template:
    metadata:
      labels:
        app: tasksappui
    spec:
      containers:
      - name: tasksappui
        image: pasupathydeva/taskappui:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: tasksappui-svc
spec:
  selector:
    app: tasksappui
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
